### ISSUE TITLE
Enhancement and/or Improvement 

### ISSUE THREAD

**Issue by Yuma-Tsushima07** [A-R-S-C-H/A.R.S.C.H.#12]
Add more utility and moderation commands. 
#### Moderation
- [ ] Ban user
- [ ] Mute user
- [ ] Purge
- [ ] Warn
#### Utility 
- [ ] Serverinfo
- [ ] Userinfo
- [ ] Bot Owner info 

I hope your project goes well :)

**Comment by DonIsCoding** [comment]
Will be moved to a plugin so in a seperate repo
